### ISSUE TITLE
As prospective student, I want to see well laid out project website, so I know this is for real

### ISSUE THREAD

**Issue by sumeetpareek** [sumeetpareek/new-money-teacher#1]
### Tasks

- [ ] push a vanilla ember project
- [ ] replace default welcome page with `new money teacher` name and images
- [ ] release it on github pages
